spring:
  datasource:
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:skillbox_team13}
  liquibase:
    enabled: true
    change-log: db/db.yml
    contexts: prod
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAILPASS}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

jwt:
  token:
    secret: ${JWT_SECRET}
    ordinary:
      expired: 3600000
    recovery:
      expired: 300000
    mail:
      expired: 300000

#осуществлять отправку писем подтверждения регистрации и сброса пароля
email.sender.active: false

server:
  port: ${PORT:8080}

#сервер на котором развернут фронт(https://team13.herokuapp.com или http://localhost:8080 при расположении в static)
server.base_url: ${BASE_URL:http://localhost:8080}

google:
  captcha:
    secret: ${GOOGLE_SECRET}
    url: https://www.google.com/recaptcha/api/siteverify

s3:
  accessKey: ${ACCESS_KEY}
  secretKey: ${SECRET_KEY}

logging:
  level:
    liquibase: INFO
    org:
      springframework: INFO
      hibernate: INFO
    ru:
      skillbox: DEBUG
  pattern:
    console: "%date{dd.MM-HH:mm:ss.SSS} %highlight(%5level) [%thread] %logger{45}: %message %n"
